### ISSUE TITLE
Intel dependencies

### ISSUE THREAD

**Issue by gnewton** [sdsc/biotools-roll#3]
Hello,

My group (bioinformatics group at Agriculture and Agri-Food Canada) are running Rocks and looking at perhaps adopting your rolls holus-bolus. But we do not have the Intel compiler suite or mkl libraries. Is this a show-stopper for us moving forward in using your rolls, especially this roll (biotools-roll), or is it (easily) possible to build your rolls without them? 

Thanks,
Glen

**Comment by jjhayes** [comment]
As of commit 9d4842e43b03977c5d2e0e329e299c64cc15f844 (June 20), the biotools-roll now builds with the gnu compiler.  I believe that the redistributable mkl libraries are still required; building the intel-roll with ROLLNAME=mkl and installing the resulting iso will supply these.
